// <auto-generated />
namespace Vendedor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DadosPessoaisPF_Endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DadosPessoaisPF_Endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201606241941290_DadosPessoaisPF_Endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
