// <auto-generated />
namespace Vendedor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correcao_Bairro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correcao_Bairro));
        
        string IMigrationMetadata.Id
        {
            get { return "201606231224103_Correcao_Bairro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
